name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41e2d91a88f5bc2fa1ebcb840bde2febd17eff06318c3ed4e7d1da415b1256b4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
