name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39604a45003d617bb62ecf06227ed0a08739c24df561b37d91e0206e603eb17d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
