name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7f2fc0aa2663c2b86c3db3dd7b42a64a57afd3159367788b878f5aa57e1b8da"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
