name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abed461faf5af0d2f744899bee3a1d8e70e45d69de78ff6ae268731c57385bfb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
