name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f70dc3c30194006e6699e2554c93a6061ee37a928b361a8013ab1ac3c3b5e7dc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
