name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26060642a40b178749bad3fd31231c87f92746013c6cd3e072b87e75dd7fc3eb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
