name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24570cf9206bcd20ceb4def11aa0eba9878fa78d5c02e929c80a7a4e14cec73c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
