name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "143072e253523b0a7d7f9d227f86b92ae200afbff7b927f404656cf8409c8af8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
