name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c6bd824fadda6a86c72f227a62344e3c5a1d316f219333e038d84a9469b13d4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
