name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c90ee16dbe493356e1f35302794204d80074eb56070fccd10668676cc8a975fa"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
