name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "281769dfaf191c8efe83a3d37d2e1ba98f0563d1dfeb7f0288899f4a420a2ac2"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
