name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f261a4b5d74a71596d7974f9bee4b9536b105b162c07296aac93bba909158aa7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
