name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9193de275bed943c9d9b2d63cde6a4fcc725d52b9e9918685fee771cdf8f9261"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
