name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7957fafa48c41b507438912df5eeb2ccac1dab8019f079875614a2066f4414af"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
