name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f196d2a0c7f8e6c065028e64f1f857bc9b81eb2843e6dbc7a6e64def10b89c96"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
