name = "MedievalCraft"
author = "torcher"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0148ddf7320f585a74a097926882dd8da1cbac1902b65a61acd6c2701a4b007c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
